#+TITLE: 程序员修炼之道

* 软件开发的变化并不大
  
  采用更能保证开发结果的方法论，多以敏捷技术为基础。

  更动态的语言（比如 Python 和 Ruby）的普及率上升。

  优秀的程序员都会采用务实和实践的方法。

  他们知道变化越多，掌握事物的基本原则就越重要。

* 前言

  本书将告诉你怎样以一种你能够遵循的方式去编程。

  怎样通过某种编程语言进行表达——这当然重要，但却只是程序员所做的事情的一小部分。

  编程是一项充满了各种细节的工作，追踪这些细节需要专注。

  在做某件事时，要把注意力投注在所做的事情上——然后尝试着把它做得更好。

  模式就是解决方案。

* 序
  
  成为更好的程序员。

  更好地完成工作。

  利用经验做出更有见识的决策。

  编程是一种技艺。用最简单的话表述，编程可归结为让计算机做你（或你的用户）想做的事情。

  编程是艰难的工作。

  不存在最佳解决方案这样一种东西，无论它是工具，是语言，还是操作系统。

  能够存在的只是在某些特定情形下更为适宜的系统。

  我不该局限于任何特定的技术，而是拥有足够广博的背景和经验基础，以让我能在特定的情况下选择好的解决方案。

  我的背景源自对计算机科学的基本原理的理解，而我的经验来自广泛的实际项目。

  理论和实践的结合使我强大起来。

  我要调整我的方法，以适应当前的情形与环境。我要判读对项目有影响的所有的因素的相对重要性，并利用我的经验制定适宜的解决方案。

  我要随着工作的进展持续不断地进行这样的活动。

  注重实效的程序员不仅要完成工作，而且要完成得漂亮。

* 谁应该阅读本书

  想变得更为有效、更多产的程序员。

* 注重实效的程序员有哪些特征

** 早期的采纳者／快速的改编者
   
   我要具有技术和技巧上的直觉，我要喜爱尝试各种事物。

   给我一样新东西，我要很快就能把握它，并把它与我的知识的其余部分结合在一起。

   我的自信出自经验。

** 好奇

   我要喜欢提问。

   我是收集小知识的林鼠，每一条小知识都可能影响今后几年里的决策。
   
** 批判的思考者

   我不会不首先抓住事实而照搬别人的说法。

** 有现实感

   我要设法理解我面临的每个问题的内在本质。
   
   这样的现实注意会给我良好的感知能力：事情有多困难，需要多长时间？

   让自己了解某个过程会有困难，或是要用一点时间才能完成，能够给予你坚持不懈的毅力。

** 多才多艺

   我要尽力熟悉广泛的技术和环境，并且努力工作，以与各种新发展并肩前行。

   尽管我现在的工作也许只要求我称为某方面的专才，我要总是能够转向新的领域和新的挑战。

** 关心你的技艺

   我要能漂亮地开发出软件。

** 思考你的工作

   在我做某件事情的时候思考我在做什么。

   我要对每一天、在每一次开发上所做出的每一项决策批判评估。

   不要依靠自动驾驶仪。

   不间断地思考，实时地批判我的工作。

* 它是一个持续的过程

  持续地做出许多小改进。
  
  每天为我所拥有的技能而工作，为把新的工具增加到我的技能列表中而工作。


   
